### PR TITLE
Fix auth0 tenant flags so it only sends set values

### LINKED ISSUE #54: auth0_tenant flags not working as expected
From terraform-provider-auth0 created by [ccogan-lh](https://github.com/ccogan-lh): alexkappa/terraform-provider-auth0#491  

### Description

When defining a tenant, I provide the flags.enable_client_connections parameter and have it be false.  Terraform applies with no issue, but within the Auth0 console I see this is toggled to true.  Terraform does not see the delta and says no issue.  I can manually flip the state on Auth0 and Terraform still does not see the issue.

### Terraform Version

```
╰─ terraform -v
Terraform v1.1.2
on darwin_amd64
```

### Affected Resource(s)

* auth0_tenant

### Terraform Configuration Files

```hcl
resource "auth0_tenant" "project" {
  picture_url   = "https://project.com/images/main-logo.png"
  support_email = "engineering@project.com"
  flags {
    enable_client_connections = false
  }
}
```

### Expected Behavior

New tenant should exist with client_connections = disabled

### Actual Behavior

New tenant exists client_connections = true and does not properly track deltas

### Steps to Reproduce

1. `terraform apply`
2. Inspect Auth0 UI tenant settings to see flag is still true

### Debug Output

N/A ? 

### Panic Output

N/A

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by sergiughf**
## Description

Fixes: #137 
Fixes: #127 
Fixes: #63 
Fixes #54 

Fix auth0 tenant flags so it only sends set values.

## Checklist

**Note:** Checklist required to be completed before a PR is considered to be reviewable.

#### Auth0 Code of Conduct
- [x] I have read and agreed to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

#### Auth0 General Contribution Guidelines
- [x] I have read the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

#### Changes include test coverage?
- [ ] Yes
- [x] Not needed

#### Does the description provide the correct amount of context?
- [x] Yes, the description provides enough context for the reviewer to understand what these changes accomplish

#### Have you updated the documentation?
- [x] Yes, I've updated the appropriate docs
- [ ] Not needed

#### Is this code ready for production?
- [x] Yes, all code changes are intentional and no debugging calls are left over

### CODE REVIEW

File: auth0/resource_auth0_tenant.go [hunk 1]
```diff
@@ -285,7 +285,7 @@ func readTenant(ctx context.Context, d *schema.ResourceData, m interface{}) diag
 }
 
 func updateTenant(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
-	tenant := buildTenant(d)
+	tenant := expandTenant(d)
```
Comment (sergiughf) [inline auth0/resource_auth0_tenant.go:288]: Renaming so we use the same terminology as the official terraform docs e.g. expanding when constructing the payload to send to the API and flattening when we deconstruct it to store into state.

File: auth0/resource_data.go [hunk 2]
```diff
@@ -257,13 +257,25 @@ func Float64(d ResourceData, key string, conditions ...Condition) (f *float64) {
...
 	if ok && Any(conditions...).Eval(d, key) {
 		b = auth0.Bool(v.(bool))
 	}
 	return
 }
 
+// Flag accesses the value held by the bool flag key
+// and type asserts it as a pointer to a bool.
+func Flag(d ResourceData, key string, conditions ...Condition) (b *bool) {
+	v, ok := d.GetOk(key)
```
Comment (sergiughf) [inline auth0/resource_data.go:272]: The issue with the flags was that they were using GetOkExists to check if the bool value was set or not which actually defaults to false when the flag is not set forcing the entire payload to be sent as the flags are pointers to bool and omitempty will only omit nil values. 

Even tho GetOkExists is deprecated in the sdkv2 we need to keep using it for all the other bool fields we have on other structs. See https://github.com/hashicorp/terraform-plugin-sdk/issues/817 for more details.

File: auth0/structure_auth0_tenant.go [hunk 3]
```diff
@@ -113,22 +115,24 @@ func expandTenantErrorPage(d ResourceData) *management.TenantErrorPage {
 }
 
 func expandTenantFlags(d ResourceData) *management.TenantFlags {
-	var flags management.TenantFlags
+	var flags *management.TenantFlags
```
Comment (sergiughf) [inline auth0/structure_auth0_tenant.go:118]: By changing this to a pointer and only setting the flags if we have the flags list set in the terraform config, we won't force the flags to be sent as an empty object any more to avoid the 400 bad requests error we get from the API in case we don't have any flags sent within. This truly makes the flags now optional as the docs indicate.

File: auth0/resource_data.go [hunk 4]
```diff
@@ -257,13 +258,27 @@ func Float64(d ResourceData, key string, conditions ...Condition) (f *float64) {
...
 	}
 	return
 }
 
+// Flag accesses the value held by the bool flag key
+// and type asserts it as a pointer to a bool.
+func Flag(configFlags cty.Value, key string) *bool {
+	configFlag := configFlags.GetAttr(key)
+
+	if configFlag.IsNull() {
```
Comment (sergiughf) [inline auth0/resource_data.go:275]: Terraform Plugin SDK v2 uses github.com/hashicorp/go-cty/cty under the hood and because of that we are now able to distinguish between values that are set in the config (true/false) and nil values (not present in the config) correctly making sure we also omit them from the PATCH payload if not present in the config.

File: auth0/structure_auth0_tenant.go [hunk 5]
```diff
@@ -112,23 +115,27 @@ func expandTenantErrorPage(d ResourceData) *management.TenantErrorPage {
...
-		flags.EnablePipeline2 = Bool(d, "enable_pipeline2")
-		flags.EnableDynamicClientRegistration = Bool(d, "enable_dynamic_client_registration")
-		flags.EnableCustomDomainInEmails = Bool(d, "enable_custom_domain_in_emails")
-		flags.UniversalLogin = Bool(d, "universal_login")
-		flags.EnableLegacyLogsSearchV2 = Bool(d, "enable_legacy_logs_search_v2")
-		flags.DisableClickjackProtectionHeaders = Bool(d, "disable_clickjack_protection_headers")
-		flags.EnablePublicSignupUserExistsError = Bool(d, "enable_public_signup_user_exists_error")
-		flags.UseScopeDescriptionsForConsent = Bool(d, "use_scope_descriptions_for_consent")
+func expandTenantFlags(flagsList cty.Value) *management.TenantFlags {
+	var tenantFlags *management.TenantFlags
```
Comment (sergiughf) [inline auth0/structure_auth0_tenant.go:119]: By changing this to a pointer and only setting the flags if we have the flags list set in the terraform config, we won't force the flags to be sent as an empty object any more to avoid the 400 bad requests error we get from the API in case we don't have any flags sent within. This truly makes the flags now optional as the docs indicate.

**Review by willvedd — APPROVED** [review]
