### PR TITLE
Throw error when encountering untracked action secrets

### LINKED ISSUE #52: auth0_action: secrets are not getting added while new/update action call
From terraform-provider-auth0 created by [RishikeshDarandale](https://github.com/RishikeshDarandale): alexkappa/terraform-provider-auth0#477  

### Description

`auth0_action` secrets **most** probably do not support the update/delete of existing secrets. But, adding new is supported and this functionality is not working at this moment with resource `auth0_action`.

### Terraform Version

```console
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/alexkappa/auth0 v0.24.2
+ provider registry.terraform.io/hashicorp/local v2.0.0
```

### Affected Resource(s)

* auth0_action

### Terraform Configuration Files

```hcl
resource "auth0_action" "test-action" {
  name = "test"
  supported_triggers {
    id      = "pre-user-registration"
    version = "v2"
  }

  code    = file("test.js")
  runtime = "node16"

  dependencies {
    name    = "Dep1"
    version = "v1"
  }
  dependencies {
    name    = "Dep2"
    version = "v2"
  }

  secrets {
    name  = "SOME_KEY"
     value = "SOME_VALUE"
  }

  deploy = true
}
```

### Expected Behavior

- `terraform import` should get the secret key read into the state file
- `terraform apply` should add the new secret to the action

#### Use Cases

- import existing `action` having one secret
- create a new `action` with one secret
- update a existing `action` to add a new secret

> Note: In all cases, `terraform` (internally auth0 mgmt API) should not be deleting/updating existing secrets.

Above observation is based on the events that were recorded #470 as below. 
- Import action resource with secret and code does not have secret
- later resource has secret added, shown in plan; 
- PATCH api body does not have secret added. 
- PATCH call successful
- The existing secret is still there, thus above observation holds true.

### Actual Behavior

- `terraform import` is not importing the secret with only key into terraform state
- `terraform apply` is not passing the new secrets to HTTP PATCH call for action update.

### Steps to Reproduce

1. `terraform apply`

### Debug Output

Please refer #470 and #472 for more debug details!

### References

- #470 
- #472

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by sergiught**
## Description

Fixes #52 

Although we can already update and create secrets as this was patched before the repo transfer, because we cannot import the values of the secrets we run the risk of erasing the secrets that are found already in the Auth0 Dashboard for the action. 

In this PR we are trying to prevent that from happening in case there are secrets that are not managed through terraform by throwing an error while updating. 

## Checklist

**Note:** Checklist required to be completed before a PR is considered to be reviewable.

#### Auth0 Code of Conduct
- [x] I have read and agreed to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

#### Auth0 General Contribution Guidelines
- [x] I have read the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

#### Changes include test coverage?
- [x] Yes
- [ ] Not needed

#### Does the description provide the correct amount of context?
- [x] Yes, the description provides enough context for the reviewer to understand what these changes accomplish

#### Have you updated the documentation?
- [x] Yes, I've updated the appropriate docs
- [ ] Not needed

#### Is this code ready for production?
- [x] Yes, all code changes are intentional and no debugging calls are left over

### CODE REVIEW

**Review by Widcket — APPROVED** [review]

**Review by Widcket — APPROVED** [review]

File: auth0/resource_auth0_action.go [hunk 1]
```diff
@@ -251,6 +259,61 @@ func deployAction(ctx context.Context, d *schema.ResourceData, m interface{}) di
...
+	preUpdateAction, err := api.Action.Read(d.Id())
+	if err != nil {
+		return diag.FromErr(err)
+	}
+
+	oldSecrets, newSecrets := d.GetChange("secrets")
+
+	return checkForUnmanagedActionSecrets(
+		oldSecrets.([]interface{}),
+		newSecrets.([]interface{}),
```
Comment (willvedd) [inline auth0/resource_auth0_action.go:276]: What is the reasoning behind casting these secrets to `[]interface{}`? Especially since these arguments get casted into a `map[string]interface{}` below. As an actionable takeaway, I think I'd prefer to see the type casting consolidated into a singular step and/or the parameter types made to be more explicit. Otherwise, it's difficult to follow the flow of logic.

File: auth0/resource_auth0_action.go [hunk 2]
```diff
@@ -251,6 +259,61 @@ func deployAction(ctx context.Context, d *schema.ResourceData, m interface{}) di
...
+		secretKeyName := oldSecret.(map[string]interface{})["name"].(string)
+		secretKeysInConfigMap[secretKeyName] = true
+	}
+
+	for _, newSecret := range newSecretsFromConfig {
+		secretKeyName := newSecret.(map[string]interface{})["name"].(string)
+		secretKeysInConfigMap[secretKeyName] = true
+	}
+
+	var warnings diag.Diagnostics
```
Comment (willvedd) [inline auth0/resource_auth0_action.go:298]: `warnings` is a bit of a misnomer because this collection only will contain errors. I think the convention we've begin to establish is to refer to a collection of `diag.Diagnostics` as `var diags diag.Diagnostics` because they could, in theory, contain both warnings and errors.

File: auth0/resource_auth0_action.go [hunk 3]
```diff
@@ -251,6 +259,61 @@ func deployAction(ctx context.Context, d *schema.ResourceData, m interface{}) di
...
+	for _, secret := range secretsFromAPI {
+		if _, ok := secretKeysInConfigMap[secret.GetName()]; !ok {
+			warnings = append(warnings, diag.Diagnostic{
+				Severity: diag.Error,
+				Summary:  "Unmanaged Action Secret",
+				Detail: fmt.Sprintf(
+					"Found unmanaged action secret with key: %s. "+
+						"Add this secret to your configuration so it does not get wiped.",
```
Comment (willvedd) [inline auth0/resource_auth0_action.go:306]:
```suggestion
					"Detected an action secret not managed though Terraform: %s. If you proceed, this secret will get deleted. It is required to add this secret to your action configuration to prevent unintentionally destructive results.",
```

File: auth0/resource_auth0_action.go [hunk 4]
```diff
@@ -251,6 +259,61 @@ func deployAction(ctx context.Context, d *schema.ResourceData, m interface{}) di
...
+
+	for _, oldSecret := range oldSecretsFromConfig {
+		secretKeyName := oldSecret.(map[string]interface{})["name"].(string)
+		secretKeysInConfigMap[secretKeyName] = true
+	}
+
+	for _, newSecret := range newSecretsFromConfig {
+		secretKeyName := newSecret.(map[string]interface{})["name"].(string)
+		secretKeysInConfigMap[secretKeyName] = true
+	}
```
Comment (willvedd) [inline auth0/resource_auth0_action.go:296]: Suggestion: combine old secrets and new secrets into single slice and consolidate into single loop.

File: auth0/resource_auth0_action.go [hunk 5]
```diff
@@ -251,6 +259,61 @@ func deployAction(ctx context.Context, d *schema.ResourceData, m interface{}) di
...
+		preUpdateAction.Secrets,
+	)
+}
+
+func checkForUnmanagedActionSecrets(
+	oldSecretsFromConfig []interface{},
+	newSecretsFromConfig []interface{},
+	secretsFromAPI []*management.ActionSecret,
+) diag.Diagnostics {
+	secretKeysInConfigMap := make(map[string]bool, len(secretsFromAPI))
```
Comment (willvedd) [inline auth0/resource_auth0_action.go:286]: I'm still figuring out the logic below, but not sure about setting the length to the number of secrets on remote. Couldn't the number of secrets in old and new be greater than the number on remote, thus making this code susceptible to out-of-bounds errors?

File: auth0/resource_auth0_action.go [hunk 6]
```diff
@@ -251,6 +259,61 @@ func deployAction(ctx context.Context, d *schema.ResourceData, m interface{}) di
...
+	if !d.HasChange("secrets") {
+		return nil
+	}
+
+	preUpdateAction, err := api.Action.Read(d.Id())
+	if err != nil {
+		return diag.FromErr(err)
+	}
+
+	oldSecrets, newSecrets := d.GetChange("secrets")
```
Comment (willvedd) [inline auth0/resource_auth0_action.go:272]: What does "old" and "new" mean in this context? Is it the union of current, added and removed? If we're just trying to calculate all secrets that are and were managed, it might not make sense to continue to separate by "new" and "old" beyond this point because that really won't impact the logic below. 

My suggestion, assuming my understanding is correct, is to consolidate these into a single slice to simplify the logic below.

File: auth0/resource_auth0_action_test.go [hunk 7]
```diff
@@ -179,3 +198,74 @@ resource auth0_action my_action {
 	}
 }
 `
+
+func TestCheckForUntrackedActionSecrets(t *testing.T) {
```
Comment (willvedd) [inline auth0/resource_auth0_action_test.go:202]: These test cases are sensible IMO. However, I'm noticing that there are no cases where `givenOldSecretsConfig` is not empty, which solidifies my point above that the separation of old and new isn't needed.

File: auth0/resource_auth0_action_test.go [hunk 8]
```diff
@@ -179,3 +198,74 @@ resource auth0_action my_action {
...
+					Severity: diag.Error,
+					Summary:  "Unmanaged Action Secret",
+					Detail: "Found unmanaged action secret with key: anotherSecretName. " +
+						"Add this secret to your configuration so it does not get wiped.",
+					AttributePath: cty.Path{cty.GetAttrStep{Name: "secrets"}},
+				},
+			},
+		},
+	}
+
```
Comment (willvedd) [inline auth0/resource_auth0_action_test.go:259]: Perhaps an additional test case would be if intentionally attempting to delete an action secret? Although, if you consolidate the old and new secret slices, you may not be able to express that as a test case. Mostly thinking out loud here!

**Review by willvedd — CHANGES_REQUESTED** [review]
Definitely an important enhancement that will prevent unintended destruction. Please excuse the volume of feedback, though it mostly revolves around a couple of minor points.

File: auth0/resource_auth0_action.go (hunk 1 above)
Comment (sergiughf) [reply auth0/resource_auth0_action.go:276]: > What is the reasoning behind casting these secrets to []interface{}?

The secrets are of type `schema.TypeList`, and that converts to a `[]interface{}` within Go. 

> Especially since these arguments get casted into a map[string]interface{} below. 

They do not, it's their elements that get casted to a `map[string]interface{}`. 

> As an actionable takeaway, I think I'd prefer to see the type casting consolidated into a singular step and/or the parameter types made to be more explicit. Otherwise, it's difficult to follow the flow of logic.

We can't, because the secrets look like this actually:

```go
secrets := []interface{}{
  map[string]interface{}{
    "name": "secretName",
    "value": "secretValue",
  },
} 
// secrets is a []interface{} with len 1
// it has an element of type map[string]interface{}
```
So first we need to typecast the most outer object and then again typecast each element of the slice.

File: auth0/resource_auth0_action.go (hunk 5 above)
Comment (sergiughf) [reply auth0/resource_auth0_action.go:286]: If we specify a capacity when using make, that doesn't mean we can't exceed the capacity on items such as slices or maps, so we won't get any out of bounds error. Go behind the scenes knows to automatically increase the size if we need to add more items.

File: auth0/resource_auth0_action.go (hunk 6 above)
Comment (sergiughf) [reply auth0/resource_auth0_action.go:272]: Sure that makes sense. 

- Why do we need to get the change and not just the actual current secrets?
- If we use `d.Get()` we'll just get the secrets that are currently in the config, that means if we remove 1 we won't fetch it, but if we don't and the secret is actually on the action, we'll think that we're trying to wipe something that shouldn't get wiped, when actually we do want to wipe it. Hope this makes sense. Lmk if you have questions.

**Review by Widcket — APPROVED** [review]
